name: ðŸ› Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! :hugging_face:
  - type: textarea
    id: bug-info
    attributes:
      label: Bug description
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see! What did you think should've happened?
      value: "A bug happened! There shouldn't be!"
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: What are the steps that you took to create this bug?
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
      value: "1. "
    validations:
      required: true
  - type: textarea
    id: other-info
    attributes:
      label: Other information
      description: Other additional information such as environment, debug logs, etc.
      placeholder: |
        Here's my logs.txt:
        ```
        GET https://www.youtube.com/watch?v=dQw4w9WgXcQ -> 200
        STATUS rickrolled: true
        TROLL
        ```
    validations:
      required: false
  - type: input
    id: repro-how-often
    attributes:
      label: Reproduces how often
      description: What percentage of the time does it reproduce?
      placeholder: "100% of the time? 75% of the times? Only when I do X?"
      value: "I can reproduce this bug 100% of the time"
    validations:
      required: true
  - type: checkboxes
    id: generic-bug-report-checklist
    attributes:
      label: Prerequisites 
      description: Make sure you have done all of the following:
      options:
        - label: I have searched the [issues](https://github.com/{{ cookiecutter.username }}/{{ cookiecutter.pypi_name }}/issues) and believe that it has not already been reported
          required: true
        - label: I have made sure this bug reproduces on the latest version
          required: true
        - label: I agree to follow this project's Code of Conduct
          required: true
